# -*- coding: utf-8 -*-

MONGODB_HOST = ''
MONGODB_PORT = 27017
MONGODB_DB = ''
MONGODB_USER = ''
MONGODB_PWD = ''

MONGO_MAX_POOL_SIZE = 10
MONGO_CONNECT_TIMEOUT_MS = 1000
MONGO_SOCKET_TIMEOUT_MS = 10000
MONGO_WAIT_QUEUE_TIMEOUT_MS = 6000
MONGO_WAIT_QUEUE_MULTIPLE = 5000
